### ISSUE TITLE
Running ChromeHtmltoPDF in Windows Container

### ISSUE THREAD

**Issue by Shashankkt** [Sicos1977/ChromiumHtmlToPdf#108]
Can it run in Windows Container? If yes, can you share the dockerfile set to run it in windows container?

**Comment by Sicos1977** [comment]
Does the user that is running the code have access to this location? `C:\app\Data\profile\`

When Chrome is started in headless mode ChromeHtmlToPdfLib needs to know the port on which Chrome is listering for command. The port that Chrome uses is written to this file --> `C:\app\Data\profile\DevToolsActivePort` . If for any reason that the user that is running ChromeHtmlToPdfLib or Chrome itself has not read/write access to this location then you are getting the error you are getting now.

Did you check if the file is present overhere -> `C:\app\Data\profile\` . If not then this is the reason.

As what I said in the first post... you have some kind if rights issue,

**Comment by Shashankkt** [comment]
I used - https://portableapps.com/download#download_details to download GoogleChromePortable and used it's executable and profile in the Converter. 

In the profile path I don't see any DevToolsActivePort file, I guess this is only created when Chrome's Developer Tool is enabled and actively used else this file won't exist. This should be anyways handled by the library itself if this is the case.

**Comment by Shashankkt** [comment]
This still doesn't work, can you share a sample profile link which I can use?
