### ISSUE TITLE
Margins cannot be set to none

### ISSUE THREAD

**Issue by Ashus** [Sicos1977/ChromiumHtmlToPdf#110]
Chrome has an CLI option "--no-margins" meaning there won't be any margins by default - no white frame. This comes useful if you have a page with custom background, that touches the left edge of paper (combined with "--print-background").
This great framework sadly can't pass this parameter to the Chrome.
Please, add this option, and it will be perfect.

Also, for some people parameter "--ignore-certificate-errors" might come handy if you get the source from localhost with untrusted certificate or don't want to add self-signed to trust store of OS.

**Comment by Sicos1977** [comment]
Do you need this in the console app or in the library ... because in the library you can set whatever parameter you want.

**Comment by Ashus** [comment]
In the console app, as I need to use it from PHP, and it works almost fine.

**Comment by Sicos1977** [comment]
Can't you just set these margins to zero instead... isn't that the same?

```c#
        /// <summary>
        ///     Top margin in inches. Defaults to 1cm (~0.4 inches).
        /// </summary>
        [Option("margin-top", Default = 0.4, Required = false, HelpText = "Top margin in inches")]
        public double MarginTop { get; set; }

        /// <summary>
        ///     Bottom margin in inches. Defaults to 1cm (~0.4 inches).
        /// </summary>
        [Option("margin-bottom", Default = 0.4, Required = false, HelpText = "Top margin in inches")]
        public double MarginBottom { get; set; }

        /// <summary>
        ///     Left margin in inches. Defaults to 1cm (~0.4 inches).
        /// </summary>
        [Option("margin-left", Default = 0.4, Required = false, HelpText = "Left margin in inches")]
        public double MarginLeft { get; set; }

        /// <summary>
        ///     Right margin in inches. Defaults to 1cm (~0.4 inches).
        /// </summary>
        [Option("margin-right", Default = 0.4, Required = false, HelpText = "Right margin in inches")]
        public double MarginRight { get; set; }
```

**Comment by Ashus** [comment]
Unfortunately no, even when you set all margins to 0, chrome adds some margins it thinks are non-printable on paper. Unless you set this option in print dialog, then the margins are counted from page edges:
![image](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/11474712/d647a7c4-d5ce-4319-8c73-15a80136fe75)

**Comment by Sicos1977** [comment]
Okey I will implement this option then.

**Comment by Sicos1977** [comment]
Implemented --> https://github.com/Sicos1977/ChromiumHtmlToPdf/releases/download/3.0.0/ChromiumHtmlToPdf_v3_0_0.zip
