### ISSUE TITLE
Minor runtime/doc updates

### ISSUE THREAD

**Issue by GitHubRulesOK** [Sicos1977/ChromiumHtmlToPdf#111]
Stumbled on this
Neat implementation (even if a lot of dependencies for a portable app), so tested on Edge and tripped on this order of hurdles

runntime says 
```
Example usage:
    ChromiumHtmlToPdf ...
```
However needs `ChromiumHtmlToPdfconsole` as the exe to run (yes I could rename but was confusing)

expected it would default to normal MSEdge so had to add that too

```
ChromiumHtmlToPdfConsole --chromium-location "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" ....
```

result was then much as expected but MSEdge --headless will default to local A4 thus I will need to add those over-rides too and now with all those long --switches its increasing looking like getting closer and closer to windows command line limit failure

tiny spelling change
>--tempfolder                        A folder where this tool <strike>**k**</strike>an put temporary files  

correction: --tempfolder                        A folder where this tool **c**an put temporary files

P.S. Adding Chromium argument '--disable-gpu' should not now be needed, but could be an option for 5 year ago chromium's

BUG ?

"C:\Apps\PDF\ChromiumHtmlToPdf\ChromiumHtmlToPdfConsole.exe" --chromium-location "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --paper-format A4 --input https://www.google.nl --output "C:\Apps\PDF\ChromiumHtmlToPdf\googleA4.pdf

**P.P.S. testing Format A4 failed (not recognised as A4 format in viewer) as it produced 21.1 when it should have been 21.0 wide** actual from PDF says 598.1 x 841.9 pt (too wide) real internal **/MediaBox [0 0 598.08002 841.91998]**

![image](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/12754913/26da4357-3cec-4ebe-bbf4-de8a071730fa)

Worse when reported by Edge !! they seem to be confused between px=nominal 96 units and point=default 72 units and have thus overquoted by 1.333%

![image](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/12754913/87a610fc-859c-46a0-b23a-8d8c8490e570)

Overall interesting alternative to MSedge --headless

**Comment by GitHubRulesOK** [comment]
Looks like it comes from here 
https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/089f0cfd4f43966f5d434f162c8fede79a1cab01/ChromiumHtmlToPdfLib/Settings/PageSettings.cs#LL223C17-L224C31

```
                case PaperFormat.A4:
                    PaperWidth = 8.3;
                    PaperHeight = 11.7;
                    break;
```
8.3 = 210.82 mm thus out of tolerance should be 8.2677 for 210 mm
11.7 = 297.18mm (borderline) should be 11.6929 for 297 mm

**Comment by Sicos1977** [comment]
Everywhere where I look on the internet uses the inch sizes I'm using now. So I stick with those. If you have another page that gives other measurements them please post them below

**Comment by GitHubRulesOK** [comment]
Adobe do not help in there way of definitions but for example the description here is 8.27 x 11.67 https://www.adobe.com/uk/creativecloud/design/discover/a4-format.html#:~:text=A4%20paper%20are-,8.27%20x%2011.67%20inches,-and%20they%20conserve
