### ISSUE TITLE
Authorization Token

### ISSUE THREAD

**Issue by rampouch-martin** [Sicos1977/ChromiumHtmlToPdf#114]
Hi,
is there any way to pass an Bearer authorization token?

**Comment by Sicos1977** [comment]
You mean in the request headers?

**Comment by rampouch-martin** [comment]
Yes, I mean the request headers,
I'm sending a request to my API, so I need to authorize it somehow.

**Comment by Sicos1977** [comment]
Uhm... at the moment I don't think it is possible or you need somehow do it with some javascript.

I'll have to look into the Chromium manual if there is an option that I can implement to add support for this.

https://chromedevtools.github.io/devtools-protocol/

**Comment by Sicos1977** [comment]
I think this is what is needed --> https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setExtraHTTPHeaders

**Comment by rampouch-martin** [comment]
I'll check it out,
Thank you.

**Comment by Sicos1977** [comment]
It is still something I have to implement to make it work for you

**Comment by Sicos1977** [comment]
I added an option for it in the latest release
