### ISSUE TITLE
Unclear usage of --input-is-list

### ISSUE THREAD

**Issue by FernandoHorna** [Sicos1977/ChromiumHtmlToPdf#116]
Thanks for this program, it is an excellent improvement of wkhtmltopdf. However it's is not quite clear what exactly is the correct syntax for the program to recognize a list of input files. Is it expecting a list such as (file1.html, file2.html)?, is it expecting a text file that contains the name of all the files?, is it expecting something like "*.html". Because if I run something like this in the folder that contains all the html files (having ChromiumHtmlToPdfConsole as an environment variable of course):

```
for /R %%i in (*.html) do ChromiumHtmlToPdfConsole --input "%%i" --output "C:\output\%%~ni.pdf"
```

Then the --multi-threading and --max-concurrency-level will be of no use and it would be very nice to use them.

If you could clarify this I would be very grateful. Thanks in advance.

**Comment by Sicos1977** [comment]
It expects a text file with a list of files you want to convert.

**Comment by fabioren** [comment]
Can you give an example for the console version?
