### ISSUE TITLE
Best way to improve performance?

### ISSUE THREAD

**Issue by davidp-silva** [Sicos1977/ChromiumHtmlToPdf#118]
Best way to improve performance?

Hello everyone, is there any way that I can reuse the same chrome to generate the PDF and thereby improve performance?

I'm currently doing it like this:

<img width="451" alt="image" src="https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/2754580/b8f6108d-d997-480f-9d35-097745a157ae">

Thank you!!!

**Comment by Sicos1977** [comment]
Just make the Convert "global" and keep calling the `ConvertToPdf` method. It will then re-use the exesting Chrome instance.
