### ISSUE TITLE
How to set dimensions

### ISSUE THREAD

**Issue by RevealedSoulEven** [Sicos1977/ChromiumHtmlToPdf#122]
Suppose I need the PDF in portrait instead of landscape or use custom dimensions. What to do :(

**Comment by Sicos1977** [comment]
You can use the pagesettings object for that --> https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/master/ChromiumHtmlToPdfLib/Settings/PageSettings.cs

**Comment by RevealedSoulEven** [comment]
Thanks for the reply sir

**Comment by RevealedSoulEven** [comment]
How to do that in cmd??
Or I need to build it
