### ISSUE TITLE
WebSocket tiemout error on large HTML

### ISSUE THREAD

**Issue by dolivaw** [Sicos1977/ChromiumHtmlToPdf#123]
Hello, 

I am using the library to generate PDFs from very large HTML files. The conversion is giving me an error, and upon reviewing the generated logs and the library's code, I believe the issue is related to a WebSocket timeout error. 

I have conducted tests with smaller data and confirmed the situation. 

I noticed that in the Connection class, you create a ClientWebSocket without specifying any options, resulting in a 30-second timeout. 

Is it possible to modify the library to allow specifying the timeout duration as a parameter?  This would involve modifying the KeepAliveInterval property of the Websocket Options object. 

Thank you very much.

 Regards.

**Comment by Sicos1977** [comment]
I added an option for this

```c#
    /// <summary>
    ///     The timeout in milliseconds when waiting for a websocket to open
    /// </summary>
    /// <remarks>
    ///     Default 30 seconds
    /// </remarks>
    public int WebsocketTimeout { get; set; } = 30000;
```

**Comment by dolivaw** [comment]
Thank you very much for the enhancement
