### ISSUE TITLE
ConvertToPdf not working in 3.1.5

### ISSUE THREAD

**Issue by kadyrkulovr** [Sicos1977/ChromiumHtmlToPdf#124]
Code:
```
using var converter = new Converter();

            PageSettings pageSettings = new(ChromiumHtmlToPdfLib.Enums.PaperFormat.A4)
            {
                PrintBackground = true,
                DisplayHeaderFooter= true,
                FooterTemplate = @"<div style=""color: lightgray; border-top: solid lightgray 1px; font-size: 12px; padding-top: 10px; text-align: center; width: 100%;""><span>Стр.</span> <span class=""pageNumber""></span> <span>из</span> <span class=""totalPages""></div>",
                MarginBottom = 0.6,
                MarginTop = 0.6,
                MarginLeft = 0,
                MarginRight = 0
            };

            using var stream = new MemoryStream();
            converter.ConvertToPdf(html, stream, pageSettings, logger: _logger);
```

Chrome version: Version 117.0.5938.89 (Official Build) (64-bit)

Logs:

> [17:14:13 INF] Starting Google Chrome from location 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' with working directory 'C:\Program Files (x86)\Google\Chrome\Application'
> [17:14:13 INF] "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless="new" --disable-gpu --hide-scrollbars --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --disable-crash-reporter --remote-debugging-port="0" --window-size="1366,768"
> [17:14:13 INF] Google Chrome process started
> [17:14:14 INF] Google Chrome exited unexpectedly, arguments used: --headless="new" --disable-gpu --hide-scrollbars --mute-audio --disable-background-networking --disable-background-timer-throttling --disable-default-apps --disable-extensions --disable-hang-monitor --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --disable-crash-reporter --remote-debugging-port="0" --window-size="1366,768"
> [17:14:14 INF] Process id: 1340
> [17:14:14 INF] Process exit time: 2023-09-22T17:14:14.237
> [17:14:14 INF] Exception:
> [17:14:14 INF] Exception: Google Chrome exited unexpectedly,
> 
> [17:14:14 INF] Error: Google Chrome exited unexpectedly,
> '
> [17:14:14 INF] Google Chrome closed gracefully
> [17:14:14 ERR] error
> ChromiumHtmlToPdfLib.Exceptions.ChromiumException: Google Chrome exited unexpectedly,
>    at ChromiumHtmlToPdfLib.Converter.StartChromiumHeadless()
>    at ChromiumHtmlToPdfLib.Converter.Convert(OutputFormat outputFormat, Object input, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger)
>    at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(String html, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger)

**Comment by kadyrkulovr** [comment]
@Sicos1977 This error occurs in version 3.1.5 only when Google Chrome already opened during debugging. If I close my browser then it works successfully. In version 2.6.7 it works in both scenarios.

**Comment by kadyrkulovr** [comment]
@Sicos1977 I changed the headless argument from `--headless=new` back to `--headless` in the method `Converter.ResetChromiumArguments()` and it solved the issue.
Thank you.

**Comment by Sicos1977** [comment]
I shall add a new property so that you can revert back to the "old" headless mode. In Edge I needed the new headless mode to make it work so we are in a split situation now :-)

Old headless mode to make it work on Chrome and the new headless mode to make it work on Edge

**Comment by Frefrec** [comment]
@Sicos1977, I have same error. However, changing the headless argument from` --headless=new` to `--headless` doesn't solve my problem.
On the other hand, I have removed the `--disable-gpu` argument. So chromium started correctly.
In addition, according to the documentation here : [,](https://peter.sh/experiments/chromium-command-line-switches/) it seems that the following arguments are no longer used: `--disable-crash-reporter --remote-debugging-port="0" --window-size="1366,768" --disable-sync --disable-translate`

**Comment by Sicos1977** [comment]
That is old documentation. I used that one in the past.

If you can give me an officicial Chromium post with needed parameters then I'm happy to remove obsolete ones. Other wise I just stick with what I have done now. You always have the option to add or remove parameters yourself.

**Comment by Sicos1977** [comment]
I added the option


```c#
    /// <summary>
    ///     By default the Chromium based browser is started with the <c>--headless=new</c> argument.
    ///     If you don't want this then set this property to <c>true</c>
    /// </summary>
    /// <remarks>
    ///     https://developer.chrome.com/articles/new-headless/
    /// </remarks>
    public bool UseOldHeaslessMode { get; set; }
```

**Comment by Frefrec** [comment]
Hello,
It seems to be official documentation.  If you go to this page:
https://developer.chrome.com/docs/web-platform/chrome-flags/#find-out-more
and then to the "Find out more" section, you'll find a link under "List of
Chromium Command LineSwitches" to the documentation I've sent you.
In any case, ChromiumHtmlToPdf doesn't work for us and we're impatiently
awaiting the release of the new version.
Many thanks for your work

**Comment by Sicos1977** [comment]
I'm done with making everything asyc. Only thing I have left is adding  a new cache handler --> `internal class FileCacheHandler : HttpClientHandler` 

This cache handler is mainly used from the DocumentHelper class because I use native .net code to get things from the internet. I always asumed that when setting cache policies on an HttpRequest that caching then always would be used. But I was wrong. It only seems to work when the server that sends you something has added a cache header in the response headers.

So I'm now making something that just ignores the responding server and always uses the cache when you have enabled that. This is also how Chromium works.
