### ISSUE TITLE
Performance in a multi threaded environment ?

### ISSUE THREAD

**Issue by FynZ** [Sicos1977/ChromiumHtmlToPdf#126]
Hello,

I've been using `ChromiumHtmlToPdf` for some time now and it was working like a charm under low pressure but now I need to generate rather large pdf (20+ pages) and it seems that doing multiple multi threaded calls degrade performances by a factor of 10. I tried multiple things (including pooling `Converters`) but I can't find anything to make it work as I expect performance wise. I saw [this issue](https://github.com/Sicos1977/ChromiumHtmlToPdf/issues/41) but as I am hosting this as a service inside an `AspNetCore` application I'm not sure this would be of use ? Is there something am I missing ?

Thanks.

**Comment by Sicos1977** [comment]
I use my solution on a 8 core server and that one is doing thousands conversions a day ... all multi threaded so it should work without any problems

**Comment by FynZ** [comment]
I believe I'm hitting this problem when calls are really close to each others (let say a caller is requesting 10 prints within few milliseconds), here's the latest piece of code I came up with to try to tackle the performance issue, maybe there is something I'm doing wrong:

`
public class Generator
{
    private readonly ILogger<Generator> _logger;

    private readonly ConcurrentQueue<Converter> _converters;

    public Generator(ILogger<Generator> logger)
    {
        _logger = logger;

        var converters = new ConcurrentQueue<Converter>();

        for (var i = 0; i < 50; i++)
        {
            var converter = BuildConverter(_logger);

            converters.Enqueue(converter);
        }

        _converters = converters;
    }

    public Task<Stream> GenerateReport(Uri uri, PrintParameters printParameters, string? waitForStatus)
    {
        if (_converters.TryDequeue(out var converter))
        {
            return ProcessAndRequeueConverter(uri, printParameters, waitForStatus, converter);
        }

        var conv = BuildConverter(_logger);

        return ProcessAndRequeueConverter(uri, printParameters, waitForStatus, conv);
    }

    private async Task<Stream> ProcessAndRequeueConverter(Uri uri, PrintParameters printParameters, string? waitForStatus, Converter converter)
    {
        try
        {
            return await Process(converter, uri, printParameters, waitForStatus);
        }
        finally
        {
            _converters.Enqueue(converter);
        }
    }

    private static async Task<Stream> Process(Converter converter, Uri uri, PrintParameters printParameters, string? waitForStatus)
    {
        var s = new MemoryStream(1024 * 1024);

        var settings = new PageSettings(PaperFormat.A4)
        {
            PreferCSSPageSize = printParameters.PreferCSSPageSize ?? true,
            Landscape = printParameters.Landscape ?? true,
            PrintBackground = printParameters.PrintBackground ?? true,
            PageRanges = printParameters.PageRanges ?? "1-1",
            MarginBottom = printParameters.MarginBottom ?? 0,
            MarginLeft = printParameters.MarginLeft ?? 0,
            MarginRight = printParameters.MarginRight ?? 0,
            MarginTop = printParameters.MarginTop ?? 0,
            Scale = printParameters.Scale ?? 1d
        };

        var libUri = new ConvertUri(uri.ToString());

        if (waitForStatus is not null)
        {
            await Task.Run(() => converter.ConvertToPdf(libUri, s, settings, waitForWindowStatus: waitForStatus));
        }
        else
        {
            await Task.Run(() => converter.ConvertToPdf(libUri, s, settings));
        }

        s.Position = 0;

        return s;
    }

    private static Converter BuildConverter(ILogger logger)
    {
        var converter = new Converter(logger: logger);

        converter.AddChromiumArgument("--headless");
        converter.AddChromiumArgument("--force-device-scale-factor=3");
        converter.AddChromiumArgument("--no-sandbox");
        converter.AddChromiumArgument("--disable-setuid-sandbox");
        converter.AddChromiumArgument("--disable-gpu");
        converter.AddChromiumArgument("--hide-scrollbars");
        converter.AddChromiumArgument("--disable-dev-shm-usage");
        converter.AddChromiumArgument("--allow-file-access-from-files");

        converter.SetWindowSize(1920, 1080);

        return converter;
    }
}`

Note: this API is running inside a linux container

Thanks.

**Comment by Sicos1977** [comment]
Okay good that you mention it that it is running in a Linux container.

My solution is running on a Windows server inside a service.

Did you check if the CPU is not the bottle neck?

And are there pictures that you are getting from the Internet of is it just plain html?

**Comment by Sicos1977** [comment]
What you also can try is to give each converter task its own user profile folder.

**Comment by FynZ** [comment]
Thanks for mentioning the spec of your server, increase the CPU count indeed solved the problem ! (was not hitting 100% tho but still reaching 80%+). Moving to a 8 cpu instance made it work like a charm !

Thank you very much !

**Comment by Sicos1977** [comment]
Good to hear. I don't know what the previous specs of your container where but if you are hitting CPU boundaries then you are probably getting a bottleneck some were that makes everything wait for each other.

**Comment by Sicos1977** [comment]
Just to be curious for what exactly are you using the library?

**Comment by FynZ** [comment]
Well now it make sense that the html processing at chrome level was CPU bound and in the end they were all waiting in line to have their share of the CPU (hitting the need for it at roughly the same time, once the request download was complete).

I use the lib to generate PDFs from specific pages view on my website (like building a compact view that would not be suited when browsing) without having the user to hit CTRL-P.

**Comment by kadyrkulovr** [comment]
@FynZ @Sicos1977 Hi,
Using your Generator class, I noticed about 100 Background processes (chrome.exe) in the Task Manager.
It looks like the processes were not dispose properly. Should it be this way, or should the processes delete themselves after the Convert is completed?

In my case, ConcurrentQueue contains 20 items. Server 4 vCores

**Comment by FynZ** [comment]
@kadyrkulovr Hi,

I have little experience with chrome on linux but as it's a multi-process beast on Windows I wouldn't expect anything else on the other side. I ended up throwing away the pre-created Converter instances once I enabled more CPUs on my VPS since the starting time was good enough for my use and didn't try to optimize it further. Are you facing a specific issue with a simple instantiation of a `Converter` class on each printing ? I'm also doubtful my piece of code was a good idea to begin with, but @Sicos1977 most likely has more knowledge on how to optimize it than I do.

Best Regards,

**Comment by Sicos1977** [comment]
> @FynZ @Sicos1977 Hi, Using your Generator class, I noticed about 100 Background processes (chrome.exe) in the Task Manager. It looks like the processes were not dispose properly. Should it be this way, or should the processes delete themselves after the Convert is completed?
> 
> In my case, ConcurrentQueue contains 20 items. Server 4 vCores

The Chrome instances will be kept alive as long the Converter object is alive. If you want to get rid of the Chrome instances you have to dispose the object. The reason the instances are kept alive is to skip the delay you get every time you need to start a new Chrome.exe process

**Comment by kadyrkulovr** [comment]
@FynZ 
I haven't noticed any issues with the processes using a simple instantiation of the Converter class. I've been monitoring it for the last couple of days, and the number of processes has remained the same (at around 100). However, one thing that concerns me is that these processes are consuming about 25% of the CPU. 
Thank you.

@Sicos1977 
Thank you for sharing the code! I have copied it and will test it out. You can go ahead and remove it now. I appreciate your help!
