### ISSUE TITLE
Words running together when reading PDF with screen reader

### ISSUE THREAD

**Issue by tonumikk** [Sicos1977/ChromiumHtmlToPdf#128]
We are considering using ChromiumHtmlToPdf to generate accommodation letters for students with disabilities. Students who are blind or visually impaired would read the PDF letter using a screen reader (JAWS for example on Windows, or VoiceOver on a Mac). When reading the PDF with JAWS on Windows, some of the words run together. The word at the end of the line runs together with the word at the beginning of the next line. 

Here is an example how the attached paragraph is heard for a screen reader user:

> The University of Minnesota is committed to providingequitable access, and designates the DRC to determine reasonableaccommodations. The accommodations in this letter are intended to minimizebarriers and provide equitable access without compromising essential courseelements. Please contact me immediately if you have concerns about any of theaccommodations outlined in this letter so that we can explore other accessoptions. If either the student or the instructor have a concern about theaccommodation process, please follow guidance in the DRC Grievanceprocess.

Is there a way to remedy this? Seems as if new lines are not considered as spaces when using a screen reader.
![2023-10-13_16-13-50](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/1093027/2012fc5e-5dd9-4b5e-b5f3-6ff01e3728de)

**Comment by Sicos1977** [comment]
I'm not an HTML expert but my best guess to find a solution for this is to look into the CSS specifications to see if there is something to help with these cases

**Comment by Sicos1977** [comment]
Something like this? https://webaim.org/techniques/css/invisiblecontent/

**Comment by Sicos1977** [comment]
No response.... closed
