### ISSUE TITLE
Can CEF be supported?

### ISSUE THREAD

**Issue by BoyFaceGirl** [Sicos1977/ChromiumHtmlToPdf#129]
CEF can be directly packaged and embedded into the app without the need to install Chrome。

**Comment by Sicos1977** [comment]
What is CEF?

**Comment by BoyFaceGirl** [comment]
> What is CEF?

Chromium Embedded Framework (CEF). A simple framework for embedding Chromium-based browsers in other applications.


[](https://github.com/chromiumembedded/cef)

[](  https://github.com/cefsharp/CefSharp)

**Comment by BoyFaceGirl** [comment]
> What is CEF?

https://github.com/cefsharp/CefSharp

https://bitbucket.org/chromiumembedded/cef/src/master/

**Comment by Sicos1977** [comment]
I don't think that it is going to work

About
.NET (WPF and Windows Forms) bindings for the Chromium Embedded Framework

It needs something to be embedded into. 

So I close this for now but if you managed to get it to work you can always sent me a pull request
