### ISSUE TITLE
Exception when Chrome is already running

### ISSUE THREAD

**Issue by Fonsaca** [Sicos1977/ChromiumHtmlToPdf#133]
I am having the following exception when trying to convert html string to PDF:

> Google Chrome exited unexpectedly

It only happens if google chrome is already open/running.
My app is a windows forms with .net framework 4.8.1. the code:

`var pageSettings = new PageSettings();
pageSettings.MarginBottom = 0;
pageSettings.MarginLeft = 0;
pageSettings.MarginRight = 0;
pageSettings.MarginTop = 0;
using(var converter = new Converter()) {
converter.ConvertToPdf(html, saveTo, pageSettings);
}`

data types: 
- string html;
- string saveTo; (file path)

Stack Trace:

>    at ChromiumHtmlToPdfLib.Converter.<StartChromiumHeadlessAsync>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ChromiumHtmlToPdfLib.Converter.<ConvertAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChromiumHtmlToPdfLib.Converter.<ConvertToPdfAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChromiumHtmlToPdfLib.Converter.<ConvertToPdfAsync>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChromiumHtmlToPdfLib.Converter.ConvertToPdf(String html, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, ILogger logger)
   at EdiPrinter.HtmlToPdf.HtmlToPdfConverter.Convert(String html, String saveTo) in D:\Development\EdiPrinter\EdiPrinter.HtmlToPdf\HtmlToPdfConverter.cs:line 25
   at EdiPrinter.Service.EdiPrintCall1n2.Print(Edi edi) in D:\Development\EdiPrinter\EdiPrinter.Service\EdiPrintCall1n2.cs:line 44
   at EdiPrinter.Service.EdiService.ProcessEdi(QueuedEdi qEdi) in D:\Development\EdiPrinter\EdiPrinter.Service\EdiService.cs:line 108
   at EdiPrinter.Service.EdiService.TaskConsume() in D:\Development\EdiPrinter\EdiPrinter.Service\EdiService.cs:line 84

**Comment by Sicos1977** [comment]
Try switching to the old headless mode and see if that makes any difference.

**Comment by yairmelamed** [comment]
It also happens to me.. Please fix this..

**Comment by Sicos1977** [comment]
> It also happens to me.. Please fix this..

As long as I don't know why Chrome crashes I can't fix it. I use my own project in a production environment that does about 100.000 conversions each day and that runs almost without any problems.

**Comment by yairmelamed** [comment]
![error](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/16683233/d1807e30-0de5-43e0-a1cf-e9223326ae2b)

1. Maybe it happens because of a new version of chrome and you run it from an older chrome version?
2. I run it from Windows os, iis, asp.net mvc project.. I see that the common situation to me and Fonsaca is Windows os.. Maybe there is a problem in Chrome for Windows..

**Comment by Sicos1977** [comment]
What does the logging say before it crashes? Did you check the Windows Event Viewer to see if Chrome dumps an error message in there... etc...

**Comment by yairmelamed** [comment]
I don't see any error on windows log that referenced to google chrome.. but I see an error on visual studio output:
Maybe it is because chrome version? 118.0.5993.118 64bit.
You can run it on visual studio asp.net mvc to simulate the error. it occurs on any website or html string..


'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-133433038506498768): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Module was built without symbols.
Exception thrown: 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' in ChromiumHtmlToPdfLib.dll
An exception of type 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' occurred in ChromiumHtmlToPdfLib.dll but was not handled in user code
Google Chrome exited unexpectedly

**Comment by Fonsaca** [comment]
Community is a bliss.
I set the headless flag to false and worked.

`converter.UseOldHeadlessMode = true;`

Thanks

**Comment by Sicos1977** [comment]
I don't know why but sometimes that just fixes it. In my situation I use the new headless mode and have no problems at all.

**Comment by Sicos1977** [comment]
> I don't see any error on windows log that referenced to google chrome.. but I see an error on visual studio output: Maybe it is because chrome version? 118.0.5993.118 64bit. You can run it on visual studio asp.net mvc to simulate the error. it occurs on any website or html string..
> 
> 'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-133433038506498768): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Module was built without symbols. Exception thrown: 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' in ChromiumHtmlToPdfLib.dll An exception of type 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' occurred in ChromiumHtmlToPdfLib.dll but was not handled in user code Google Chrome exited unexpectedly

Are you using the Chrome Portable? The full blown installed version won't work when you execute it from IIS.

**Comment by yairmelamed** [comment]
> > I don't see any error on windows log that referenced to google chrome.. but I see an error on visual studio output: Maybe it is because chrome version? 118.0.5993.118 64bit. You can run it on visual studio asp.net mvc to simulate the error. it occurs on any website or html string..
> > 'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-133433038506498768): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Module was built without symbols. Exception thrown: 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' in ChromiumHtmlToPdfLib.dll An exception of type 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' occurred in ChromiumHtmlToPdfLib.dll but was not handled in user code Google Chrome exited unexpectedly
> 
> Are you using the Chrome Portable version? The full blown installed version won't work when you execute it from IIS. Don't ask my why it does not work because it just don't.

It occurs on chrome portable and local chrome installation..

> > I don't see any error on windows log that referenced to google chrome.. but I see an error on visual studio output: Maybe it is because chrome version? 118.0.5993.118 64bit. You can run it on visual studio asp.net mvc to simulate the error. it occurs on any website or html string..
> > 'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/1/ROOT-1-133433038506498768): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Module was built without symbols. Exception thrown: 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' in ChromiumHtmlToPdfLib.dll An exception of type 'ChromiumHtmlToPdfLib.Exceptions.ChromiumException' occurred in ChromiumHtmlToPdfLib.dll but was not handled in user code Google Chrome exited unexpectedly
> 
> Are you using the Chrome Portable version? The full blown installed version won't work when you execute it from IIS. Don't ask my why it does not work because it just don't.

It occurs on Chrome Portable version and local Chrome installation.. I checked both of them..

**Comment by Fonsaca** [comment]
Maybe in my environment, by default, chrome is running with headless=old, so it conflicts in some manner when the browser is open/running in my machine. But if the browser is closed i have no problem with headless=new.

I am using the installed version of google chrome. My app is a windows forms, so i'm not going to use IIS.
A thought in this: May the problem be related to what process the chrome is running under?. When convert to PDF is called I see in TaskManager that a new process is started under my own app's process. Is it possible to start a toatally different process?
