### ISSUE TITLE
Issue with displaying image

### ISSUE THREAD

**Issue by muhtadii** [Sicos1977/ChromiumHtmlToPdf#135]
I am trying to generate a pdf from an html page containing an image with absolute URL, using Chrome library. The pdf file is generated properly with styling intact, but the image always goes missing. Is this a known issue?

**Comment by Sicos1977** [comment]
Just open your html file with Chrome or Edge and see if you then see the image. If yes then turn on logging and post it over here so that I can see what is going on. Otherwise try to figure out why the image is not shown in Chrome or Edge

**Comment by Sicos1977** [comment]
No response... closed.
