### ISSUE TITLE
The FileCache dependency pulls in all of .NETStandard1.6 and it's libraries

### ISSUE THREAD

**Issue by EraYaN** [Sicos1977/ChromiumHtmlToPdf#136]
The `FileCache` dependency pulls in the `System.Data.HashFunction.Core` dependency which in itself is .NET Standard 1.1 and that depends on https://www.nuget.org/packages/NETStandard.Library/1.6.1 which pulls in a ton on vulnerable dependencies by default (which are also all not required).

This issue should probably track a FileCache update if they release one. This repo seems to have taken over the leaf package: https://github.com/Deskasoft/Data.HashFunction but no issue tracker so no way to get them to stop listing netstandard1.1 as the only .NET Standard version. I have sent them an email so who knows they might be open to rolling out a release.

Microsoft also recommends against targeting 1.1 https://learn.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target

Would this project be open to a version bump when `FileCache` eventually releases an updated version?

**Comment by EraYaN** [comment]
Seems like https://github.com/acarteas/FileCache/issues/60 it's abandoned somewhat.

**Comment by Sicos1977** [comment]
I'm always open to pull request otherwise I would not make this package open source :-)

**Comment by Sicos1977** [comment]
Fixed in the latest commit

**Comment by EraYaN** [comment]
@Sicos1977 System.Data.HashFunction.Core still depends on 1.6.1. I think the framework hashes should be enough for the current implementation.
