### ISSUE TITLE
ChromiumException: Google Chrome exited unexpectedly

### ISSUE THREAD

**Issue by tanzeelashfaq** [Sicos1977/ChromiumHtmlToPdf#139]
Previously i was using older version of this Package and it was working great. Now i have updated to latest version 4.1.3 and it is throwing exception "ChromiumException: Google Chrome exited unexpectedly".

I am using ASP Core 7.0.
I have installed Chrome on default location.
I am using following code to convert html to pdf.

sing (var converter = new ChromiumHtmlToPdfLib.Converter())
            {
                converter.ConvertToPdf(
                    html,
                    baseUrl,
                    new ChromiumHtmlToPdfLib.Settings.PageSettings()
                    {
                        Landscape = false,
                        DisplayHeaderFooter = false,
                        PrintBackground = true,
                        Scale = 1,
                        PaperWidth = 8.3,
                        PaperHeight = 11.7,
                        MarginLeft = 0.5,
                        MarginRight = 0.5,
                        MarginTop = 0.5,
                        MarginBottom = 0.125,
                        PageRanges = string.Empty
                    });
            }

What i am missing please let me know your help would be greatly appreciated...

**Comment by Sicos1977** [comment]
Sometimes it helps to use the old headless mode, don't ask me why but most of the servers where I use it run fine with the "new" headless mode and some just refuse to work with it.

```c#
    /// <summary>
    ///     By default the Chromium based browser is started with the <c>--headless=new</c> argument.
    ///     If you don't want this then set this property to <c>true</c>
    /// </summary>
    /// <remarks>
    ///     https://developer.chrome.com/articles/new-headless/
    /// </remarks>
    public bool UseOldHeadlessMode
    {
        get => !_defaultChromiumArgument.Contains("--headless=new");
        set
        {
            for (var i = 0; i < _defaultChromiumArgument.Count; i++)
            {
                if (!_defaultChromiumArgument[i].StartsWith("--headless")) continue;
                _defaultChromiumArgument[i] = value ? "--headless" : "--headless=new";
                return;
            }
        }
    }
```

**Comment by tanzeelashfaq** [comment]
A big thanks...
Setting converter.UseOldHeadlessMode = true; fix the issue...
