### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by welly-im** [Sicos1977/ChromiumHtmlToPdf#140]
I want to convert HTML to PDF, sometimes it succeeds, and sometimes I encounter the following error: 'Conversion failed ... did not get the expected response from Chromium, response '{"id":8,"error":{"code":-32000,"message":"Printing failed"}}'. Is there a solution to address this issue? Because out of 10 requests, 6 of them fail.

**Comment by Sicos1977** [comment]
I guess it has something todo with what you are trying to print. You can try to just print whatever you are trying to convert from Chrome as PDF and see what that does.

https://www.greengeeks.com/tutorials/save-a-web-page-as-a-pdf-in-chrome-browser/

**Comment by Sicos1977** [comment]
No response ... closed
