### ISSUE TITLE
Can we support Bootstrap CDN? I think it's not working with Bootstrap CDN.

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [Sicos1977/ChromiumHtmlToPdf#151]
Can we support Bootstrap CDN? I think it's not working with Bootstrap CDN.

While converting to PDF, It's only working with Custom CSS but not with boostrap CDN link. Can we please check this?

**Comment by Sicos1977** [comment]
I have no idea. The tool just used Chrome headless so everything that works in Chrome should work in ChromiumHtmlToPdf

**Comment by SaiGaneshKrishnan** [comment]
Okay. Will update on it.
