### ISSUE TITLE
Issue while converting HTML TO PDF (Happens while converting to Pdf via linux)

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [Sicos1977/ChromiumHtmlToPdf#154]
Exception occured while extracting data from excel. Message : Could not find Google Chrome in location ''](fail: Exception occured while extracting data from excel. Message : Could not find Google Chrome in location ''  StackTrace :    at ChromiumHtmlToPdfLib.Converter..ctor(String chromiumExeFileName, String userProfile, ILogger logger, Boolean useCache, Browser browser)).

Example of Docker File which I use:

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

# export DEBIAN_FRONTEND="noninteractive"
ENV DEBIAN_FRONTEND noninteractive

# Install deps + add Chrome Stable + purge all the things
RUN apt-get update && apt-get install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	--no-install-recommends \
	&& apt-get purge --auto-remove -y curl gnupg \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
apt-get install -y unzip && \
wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip && \
unzip chromedriver_linux64.zip && \
mv chromedriver /usr/bin && rm -f chromedriver_linux64.zip

**Comment by SaiGaneshKrishnan** [comment]
In which location it searches for chome?

**Comment by Sicos1977** [comment]
See this class --> https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/master/ChromiumHtmlToPdfLib/Helpers/ChromeFinder.cs
