### ISSUE TITLE
Some font family not supported

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [Sicos1977/ChromiumHtmlToPdf#159]
Below are font families are not supported when deploying to linux.

1. Verdana
2. Courrier New
3. Callibiri

Do we know why?

But when I run in windows platform, it's working. 

Not working only on linux system.

Docker File command as follows below:

# Suppress an apt-key warning about standard out not being a terminal. Use in this script is safe.
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

# export DEBIAN_FRONTEND="noninteractive"
ENV DEBIAN_FRONTEND noninteractive

# Install deps + add Chrome Stable + purge all the things
RUN apt-get update && apt-get install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	--no-install-recommends \
	&& apt-get purge --auto-remove -y curl gnupg \
	&& rm -rf /var/lib/apt/lists/*

# Chrome Driver
RUN apt-get update && \
    apt-get install -y unzip && \
    wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    mv chromedriver /usr/bin && rm -f chromedriver_linux64.zip

**Comment by Sicos1977** [comment]
?

**Comment by SaiGaneshKrishnan** [comment]
When converting HTML to PDF, if the HTML has font family of Verdana or Courrier New or Callibiri in CSS. Then PDF is not taking those font families. Why?

**Comment by mrrhak** [comment]
I'm not sure your required font family are existed in `ttf-mscorefonts-installer` or not but you can try it with install Microsoft fonts to Linux (docker) with this command below:
```sh
RUN apt-get update && apt-get install -y ttf-mscorefonts-installer  --no-install-recommends
```
> If you want to support emoji can add install this font more `fonts-noto-color-emoji`
```sh
RUN apt-get update && apt-get install -y ttf-mscorefonts-installer fonts-noto-color-emoji --no-install-recommends
```
