### ISSUE TITLE
Please change ChromeFinder.Find() and EdgeFinder.Find() visibility to public

### ISSUE THREAD

**Issue by Kim-SSi** [Sicos1977/ChromiumHtmlToPdf#160]
Him
Could you please change the following Find methods back to be public? Or is there a specific reason to make them internal?
```
ChromiumHtmlToPdfLib.Helpers.EdgeFinder.Find()
ChromiumHtmlToPdfLib.Helpers.ChromeFinder.Find()
```
The reason behind this request is to be able to verify that Chrome or Edge are installed and then to check the version.
If they are not installed or too old then I will need to install a portable Chrome.
I would like to use the same location finding code from your library so that in the future any changes to install paths etc are resolved the same as when happens when I use the Converter class.

Currently I am working around this using Reflection to call the Find methods.

Regards,
Kim

**Comment by Sicos1977** [comment]
There was never a reason to make them public.... until now. Normally I always make all my classes methods and properties internal  (this is also the default behaviour when you dont put an access modifier before them) when there is no reason to make them public. It is also best practice to do that according to Microsoft programming guidelines.

**Comment by Sicos1977** [comment]
In the next version you will have this static method in the converter class

```c#
    /// <summary>
    ///     Returns the location of the Chromium based browser or <c>null</c> when not found
    /// </summary>
    /// <param name="browser"><see cref="Enums.Browser"/></param>
    /// <returns></returns>
    /// <exception cref="ArgumentOutOfRangeException"></exception>
    public static string? GetChromiumLocation(Enums.Browser browser)
    {
        return browser switch
        {
            Enums.Browser.Chrome => ChromeFinder.Find(),
            Enums.Browser.Edge => EdgeFinder.Find(),
            _ => throw new ArgumentOutOfRangeException(nameof(browser), browser, null)
        };
    }
```

**Comment by Sicos1977** [comment]
Get the latest version from nuget
