### ISSUE TITLE
HTML to PDF Conversion Failed

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [Sicos1977/ChromiumHtmlToPdf#161]
ChromiumHtmlToPdfLib.Exceptions.ConversionException: Conversion failed ... did not get the expected response from Chromium, response '{"id":8,"error":{"code":-32000,"message":"Printing failed"}}' 

If we use the below PNG image in the HTML file, then conversion is failing in linux system.

Do we know why?

![Wiz Logo](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/162687393/43d2b3ef-5ba5-46a0-aa6c-ccb0e5f1b764)

**Comment by Sicos1977** [comment]
What happens when you try to save the html as pdf just from Chrome itself?

**Comment by SaiGaneshKrishnan** [comment]
Yes. Its able to save it when we do via chrome.

[EMA Radar™ Report for Digital Employee Experience Management (DEX) – Vmware- Spotlight.pdf](https://github.com/user-attachments/files/16020160/EMA.Radar.Report.for.Digital.Employee.Experience.Management.DEX.Vmware-.Spotlight.pdf)

**Comment by SaiGaneshKrishnan** [comment]
response '{"id":8,"error":{"code":-32000,"message":"Printing failed"}}'

What all cases where chromiumHTMLToPDF threw an error for the above error code? So that it would helpful for us to check on it

**Comment by SaiGaneshKrishnan** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arial TEMPLE</title>
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: Arial;
            font-size: 15px;
            font-weight: 400;
        }

        body {
            background-color: #000000;
        }

        .previewContainer {
            width: 100%;
            display: flex;
            flex-direction: column;
            margin-bottom: 5%;
        }

        .logoRow {
            height: 80px;
            text-align: Left;
            margin-left: 5%;
            margin-right: 5%;
            margin-top: 20px;
            margin-bottom: 20px;
        }

            .logoRow img {
                max-height: 100%;
                text-align: center;
                max-width: 50%;
            }

        .contentRow {
            width: 90%;
            margin-top: 50px;
            margin-left: 5%;
            margin-right: 5%;
            display: flex;
            flex-direction: row;
            column-gap: 5%;
        }

        .infoColumn {
            width: 60%;
            display: flex;
            flex-direction: column;
            color: #ffffff;
        }

        .infoColumn .heading {
            font-weight: bold;
            height: fit-content;
            font-size: 30px;
        }

        .infoColumn .imageRow img {
            margin-top: 35px;
            margin-bottom: 30px;
            max-width: 100%;
            max-height: 100%;
        }

        .infoColumn .abstract {
            font-size: 18px;
            line-height: 30px;
            text-align: justify;
        }

        .formColumn {
            width: 420px;
            display: flex;
            margin-right: 5%;
            flex-direction: column;
            border-radius: 20px;
            border: 1px solid #80808073;
            background-color: #F2F2F2;
            height: fit-content;
        }

        .formColumn .card {
            background-color: #f5f5f500;
            padding: 25px;
        }

        .formColumn .cardHeader {
            font-size: 20px;
            padding: 5px;
            margin-top: 10px;
            margin-bottom: 15px;
            font-weight: bold;
        }

        .formColumn .cardBody {
            display: flex;
            flex-direction: column;
        }

        .formColumn .cardBody .form-group {
            width: 100%;
            padding: 10px;
        }

        .formColumn .cardBody .form-group label {
            display: block;
        }

         .formColumn .cardBody .form-control {
             width: 100%;
             padding: 7px;
             margin-top: 2px;
             border: 1px solid #e0e0e0;
             border-radius: 5px;
             box-shadow: lightgrey 0px 1px 0px;
         }

         .formColumn .cardBody .form-optIn {
             margin: 5px 0px 5px 10px;
             width: 100%;
             display: flex;
             align-items: baseline;
             gap: 10px;
         }

          .formColumn .cardBody .form-downloadButton {
             padding: 10px;
             width: 100%;
             margin-bottom: 30px;
          }

        .required::after {
            content: '*';
            color: #e53935;
            margin-left: 5px;
        }

        .downloadButton {
            width: 100%;
            padding: 10px;
            background-color: #2780EB;
            color: white;
            text-decoration: none;
            text-align: center;
            border: none;
            border-radius: 10px;
            font-size: 15px;
            font-weight: bold;
            -webkit-print-color-adjust: exact;
        }

        .downloadButton:disabled {
                background-color: lightgrey;
        }

        @media (max-width: 992px) {
            .contentRow {
                flex-direction: column;
            }

            .infoColumn {
                width: 90%;
                margin: 0 5% 50px;
            }

            .formColumn {
                width: 90%;
                margin: 0 5%;
                justify-content: center;
            }
        }
    </style>
</head>

<body>
    <div class="previewContainer">
        <div class="logoRow"><img src="https://d21jslia6jvy2t.cloudfront.net/Wiz+Logo.png" alt="Logo" rel="noopener noreferrer"></div>
        <hr>
        <div class="contentRow">
            <div class="infoColumn">
                <div class="heading">Arial TEMPLE</div>
                <div class="imageRow"><img src="https://d21jslia6jvy2t.cloudfront.net/Wiz+Asset+Screen+Shot.jpg" alt="Image" rel="noopener noreferrer"></div>
                <p class="abstract">EMA Radar™ Report for Digital Employee Experience Management (DEX) – VMware Spotlight. All modern businesses are dependent on digital technologies to drive workforce productivity to achieve company performance and financial success. The principles of digital transformation and modern management suggest that digital technologies should principally support user-centric requirements and preferences to maximize business productivity. However, traditional IT management tools are not designed to fully gauge and respond to user experience issues. This Enterprise Management Associates&#174; (EMA™) Radar Report identifies the leading DEX solution providers and spotlights VMware’s Digital Employee Experience Management solution, powered by Workspace ONE Intelligence.n nLearn how Workspace ONE Intelligence enables administrators to measure, analyze, and remediate end-user experiences with machine learning-driven root cause analysis and prebuilt integrations to support endpoints and users from anywhere.</p>
            </div>
            <div class="formColumn">
                <div class="card">
                    <h3 class="cardHeader">Please complete the form to access/download the content</h3>
                    <div class="cardBody">
                        <form class="downloadForm" action="https://www.vmware.com/content/microsites/learn/en/1929501_TY.html" rel="noopener noreferrer">
                            <div class="form-group">
<label class="required">First Name</label>
<input type="text" class="form-control" required>
</div>
<div class="form-group">
<label class="required">Last Name</label>
<input type="text" class="form-control" required>
</div>
<div class="form-group">
<label class="required">Email Address</label>
<input type="email" class="form-control" required>
</div>
<div class="form-group">
<label class="required">Phone Number</label>
<input type="tel" class="form-control" required>
</div>
<div class="form-group">
<label class="required">Asset Title</label>
<select class="form-control" required>
<option value="">Please Select</option>
<option>Asset1</option>
</select>
</div>
<div class="form-group">
<label class="required">Company Name</label>
<input type="text" class="form-control" required>
</div>
<div class="form-group">
<label class="required">Opt In</label>
<select class="form-control" required>
<option value="">Please Select</option>
<option>Yes</option>
<option>No</option>
</select>
</div>
<div class="form-group">
<label class="required">Opt In Date</label>
<input type="date" class="form-control" required>
</div>

                                <div class="form-optIn">
<input type="checkbox" id="checkbox" onchange="enableDownload()">
<label>Opt in Message Added</label>
</div>
                                    <div class="form-optIn">
<a href="https://www.vmware.com/content/microsites/learn/en/1929501_TY.html" rel="noopener noreferrer">Privacy Policy</a>
</div>
                                        <div class="form-downloadButton">
                                            <button id="downloadButton" class="downloadButton" disabled>Download</button>
                                        </div>
                            </Form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            var button = document.getElementById('downloadButton');
            const form = document.querySelector('.downloadForm');
            const assetLink = form.getAttribute('action');

            if (assetLink) {
                form.setAttribute('target', '_blank');
                button.setAttribute('type', 'submit');
            } else {
                button.setAttribute('type', 'reset');
            }

            form.style.cssText = 'display: flex; flex-wrap: wrap; row-gap: 2px;';

            const formGroups = document.querySelectorAll('.downloadForm .form-group');
            const formColumn = document.querySelector('.formColumn');
            if (formGroups.length > 5) {
                formColumn.style.width = '470px';
                formGroups.forEach((formGroup, index) => {
                    formGroup.style.flex = (index === formGroups.length - 1 && formGroups.length % 2 !== 0) ? '0 0 100%' : '0 0 50%';
                });
            }

            const formColumnHeight = document.querySelector('.formColumn').clientHeight;
            const image = document.querySelector('.infoColumn .imageRow img');
            const abstractHeight = document.querySelector('.infoColumn .abstract').clientHeight;
            const headingHeight = document.querySelector('.infoColumn .heading').clientHeight;
            const newImageHeight = formColumnHeight - abstractHeight - headingHeight - 60;

            image.style.height = (newImageHeight < 300 || formColumnHeight < 400) ? '400px' : `${newImageHeight}px`;
        });
        
function enableDownload() {
var checkbox = document.getElementById("checkbox");
var button = document.getElementById("downloadButton");
button.disabled = !checkbox.checked;
}

    </script>

</body>

</html>`

For the above HTML, Please use the attached physical image. Then it's not working. 

![Wiz Asset Screen Shot](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/162687393/12429ce6-2a05-40b3-a5cd-627817730245)

![Wiz Logo](https://github.com/Sicos1977/ChromiumHtmlToPdf/assets/162687393/e545f71f-9b6e-4cbc-afb2-d950aa3d527d)

If we have URL in the place of physical image then it worked. 

But the physical image is converted into base64 and added in src tag. Then it's not working. Only for the attached images. Seems to be wierd.

**Comment by Sicos1977** [comment]
Enable Chromium logging with the **EnableChromiumLogging** property and look into that logfile to figure out why it is not working. It looks to me that it is a problem in Chromium and not something I can fix.

**Comment by Sicos1977** [comment]
No response... closed
