### ISSUE TITLE
Typo when printing exception in ChromiumHtmlToPdfLib/Converter.cs.

### ISSUE THREAD

**Issue by JBMiller** [Sicos1977/ChromiumHtmlToPdf#165]
https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/4abbb1fda34cfd4bee36fa48f408ba51306bc4a6/ChromiumHtmlToPdfLib/Converter.cs#L799

`", {exception}"` is missing the dollar sign. Should be `$", {exception}"`

**Comment by Sicos1977** [comment]
Correct... thanks
