### ISSUE TITLE
Documentation for pageSettings

### ISSUE THREAD

**Issue by Semaho** [Sicos1977/ChromiumHtmlToPdf#171]
Hi Kees,
Is there already an online doc for what can be passed through `pageSettings` ?
If yes can you add the link to the readme please ?

I found multiple things so I'm not really sure what's expected...

Thank you !

**Comment by Sicos1977** [comment]
Is your intellisense not working or did I forget to include the xml documentation in the latest version? 

Otherwise --> https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/master/ChromiumHtmlToPdfLib/Settings/PageSettings.cs

**Comment by Semaho** [comment]
Was just looking for a solution to suggest to my colleagues, I don't have the setup to test this right away :)
Thanks for link !

**Comment by Sicos1977** [comment]
No problems but I just released a new version today and thought that I forgot to add the xml documentation in the nuget package :-)

**Comment by Sicos1977** [comment]
I guess you are looking for a replacement for wkHtmlToPdf?

**Comment by Semaho** [comment]
We are looking for a proper solution to implement in a .NET/Sitecore project but nothing very modern/satisfying so far (either too complex or slow or bad). 
So I started looking for my colleagues if we could run a headless Chrome on the server and benefits from its HTML to PDF module, that's how I ended up on your package :)

**Comment by Sicos1977** [comment]
If you are missing something just let me know so that i can see if I can add it... if you want to go all the way you always can use [puppeteer.net](https://github.com/hardkoded/puppeteer-sharp) and do everything yourself. I just made this library as a replacement for wkhtmltopdf to convert html files to pdf format :-)
