### ISSUE TITLE
More Thorough Documention

### ISSUE THREAD

**Issue by cstonelight** [Sicos1977/ChromiumHtmlToPdf#175]
Could you please provide more detailed or less vague documentation? Both for the library and the console app, but specifically for syntax with the console app.

e.g.

> "Tells this app that --input is a list of input urls and/or files. Use the --output parameter to give a location where to write information about the converted files, e.g. c:\\myconvertedfiles. Use a | sign to supply an output file, e.g. inputfile.html|myoutputfile.pdf. When no outputfile is given then the input file is used as the outputfile where the extension is replaced with .pdf"

???

No combination of "|" I tried works.

**Comment by Sicos1977** [comment]
I added documentation to the readme
