### ISSUE TITLE
Printing fails when running with console app

### ISSUE THREAD

**Issue by sesa312293** [Sicos1977/ChromiumHtmlToPdf#176]
I am trying to utilize your tool through a windows server core container. I have worked through most issues and the tool is now running, but fails with this error:
Conversion failed ... did not get the expected response from Chromium, response '{"id":7,"error":{"code":-32000,"message":"Printing failed"}}'

Is there a way to get more specifics as to why it failed? I don't see any command line option to get more verbose information.

I have tried converting the same file on a Windows VM and have no issues so I know the tool can convert the html. It seems like I am still missing something in the container.

**Comment by MaceWindu** [comment]
Could be related https://github.com/microsoft/Windows-Containers/issues/219

**Comment by Sicos1977** [comment]
I also added an extra section about this in the readme --> https://github.com/Sicos1977/ChromiumHtmlToPdf/blob/master/README.md#converting-from-the-command-line

**Comment by sesa312293** [comment]
@Sicos1977, how do you set the EnableChromiumLogging flag? I don't see an option in the command line parameters.

@MaceWindu, I have seen that as well and have the "Server-Media-Foundation" feature installed, as well as the fonts mentioned.

**Comment by MaceWindu** [comment]
You could try

1. add one more option
```cs
converter.AddChromiumArgument("--disable-gpu");
```
2. run chrome printing from console directly and see which output it produce:
`chrome --headless --print-to-pdf="test.pdf" --enable-logging --v=1 "<url_or_file>"`
