### ISSUE TITLE
select edge or chrome as browser case "chrome":   code Error 

### ISSUE THREAD

**Issue by wannvmi** [Sicos1977/ChromiumHtmlToPdf#182]
namespace ChromiumHtmlToPdfConsole Program 
case "chrome":   should use chrome

![image](https://github.com/user-attachments/assets/ef27a8c6-bdc6-43b8-b219-e33cece12bf0)

**Comment by Sicos1977** [comment]
That looks like a well-known copy - paste error that developers sometimes make :-) ... I'll try to fix it this weekend and make a new console app.

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromiumHtmlToPdf/releases/download/4.2.11/ChromiumHtmlToPdf_4_2_11.zip
